### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by mkroening**

### CODE REVIEW

**Comment by tats-u** [comment]
@mkroening ~~Could you tell me whether there is no other alternative than clippy? Is it the de facto standard?~~ Ah it seems to be a de facto.

Did you check the other files? Also could you make Actions check codes using clippy?

**Comment by mkroening** [comment]
Yes, it's a de facto standard.

I added a CI step. The other files are fine, apart from `code_table.rs`, which I am currently reworking anyway for https://github.com/tats-u/rust-oem-cp/issues/7. That's why I set the CI step to `continue-on-error` for now.

**Review by tats-u — APPROVED** [review]

**Comment by tats-u** [comment]
@mkroening Looks good. Can I choose “Squash and merge”? I thought we don't have to split commits by each rule. (I'll accept all rules).

**Comment by mkroening** [comment]
> Can I choose “Squash and merge”?

Sure! Go ahead.

**Pull request merged**
